import type { CampaignSave } from './types';

export const GAME_VERSION = '0.3.14';
export const SAVE_VERSION = 5 as const;

export function createDefaultCampaign(): CampaignSave {
  return {
    saveVersion: SAVE_VERSION,
    gameVersion: GAME_VERSION,
    updatedAt: new Date().toISOString(),
    player: {
      name: 'Alexander Vane',
      age: 19,
      hp: 100,
      maxHp: 100,
      stamina: 100,
      maxStamina: 100,
      berries: 308_600,
      bounty: 6_500_000,
      position: { x: 720, y: 870 },
      equipmentTags: ['captain', 'swords', 'light-armor', 'tools'],
      equipment: { weapon: null, armor: null, tool: null, accessory: null },
      fruit: {
        eaten: true,
        fruitNameKnown: false,
        observedPower: 'attraction',
        mastery: 0.08,
        range: 270,
        force: 420,
      },
      knowledge: { hakiKnown: false },
      progression: { combatExperience: 0, physicalConditioning: 0, fruitTechniquePoints: 0, techniques: ['focused-pull'] },
    },
    crew: [
      {
        id: 'sera',
        name: 'Sera Quill',
        role: 'Navigator',
        hp: 76,
        maxHp: 76,
        position: { x: 650, y: 905 },
        loyalty: 0.62,
        morale: 0.67,
        notes: ['Cautious navigator', 'Acts independently', 'Knows the sea better than Alexander'],
        equipmentTags: ['navigator', 'light-armor', 'tools', 'light-weapons'],
        capabilities: ['navigation', 'helm'],
        equipment: { weapon: null, armor: null, tool: null, accessory: null },
        progression: { experience: 0, specialty: 0.18, techniques: ['read-the-water'] },
        recruitedDay: 1,
      },
      {
        id: 'rowan',
        name: 'Rowan Vale',
        role: 'Frontline fighter',
        hp: 110,
        maxHp: 110,
        position: { x: 780, y: 900 },
        loyalty: 0.58,
        morale: 0.74,
        notes: ['Uses chain hooks', 'Wants freedom, strength, and a name across the seas'],
        equipmentTags: ['fighter', 'chain-weapons', 'medium-armor', 'tools'],
        capabilities: ['frontline-combat'],
        equipment: { weapon: null, armor: null, tool: null, accessory: null },
        progression: { experience: 0, specialty: 0.2, techniques: ['chain-control'] },
        recruitedDay: 1,
      },
    ],
    ship: {
      name: 'Wayward Gull',
      hull: 100,
      maxHull: 100,
      supplies: 72,
      x: 760,
      y: 1600,
      heading: -Math.PI / 2,
      speed: 0,
    },
    inventory: {
      'Basic medicine': 2,
      'Fresh water': 5,
      'Rations': 5,
      'Rope': 1,
    },
    equipmentInventory: {},
    journal: [
      {
        id: 'harrow-escape',
        title: 'Escape Harrow Island',
        body: 'Reach the Wayward Gull. Marines are searching the docks; fighting is optional.',
        known: true,
      },
      {
        id: 'fruit',
        title: 'Unknown Devil Fruit',
        body: 'You swallowed the deep-blue spiral Fruit during the escape. Its observed effect pulls people and objects toward you.',
        known: true,
      },
    ],
    world: {
      scene: 'opening',
      locationId: 'harrow-island',
      day: 1,
      minuteOfDay: 17 * 60 + 24,
      flags: {
        openingSeen: false,
        harrowMarinesAlerted: false,
        harrowEscaped: false,
        gullrockDiscovered: false,
        waywardGullDisabled: false,
        sailingDelegated: true,
        shipDestination: 'gullrock',
      },
      canonLedger: [],
      islands: {
        'harrow-island': {
          id: 'harrow-island',
          name: 'Harrow Island',
          seed: 1107,
          size: 'medium',
          discovered: true,
          population: 640,
          marinePresence: 0.72,
          piratePresence: 0.12,
          prosperity: 0.46,
          danger: 0.42,
          factions: ['Harrow Marines', 'Marron family'],
          activeSituations: ['marine-search'],
          resolvedSituations: [],
          lastSimulatedDay: 1,
          region: 'east-blue',
          geography: ['rocky harbor', 'low wooded interior'],
          settlements: ['Harrow Harbor', 'inland farms'],
          resources: ['fish', 'timber'],
          opportunities: ['smuggling leads', 'dock work'],
          notableTraits: ['Marine search pressure'],
          governmentImportance: 0.58,
        },
        gullrock: {
          id: 'gullrock',
          name: 'Gullrock',
          seed: 2219,
          size: 'medium',
          discovered: false,
          population: 910,
          marinePresence: 0.24,
          piratePresence: 0.3,
          prosperity: 0.61,
          danger: 0.31,
          factions: ['Gullrock traders', 'Harbor authority'],
          activeSituations: ['north-road-thefts'],
          resolvedSituations: [],
          lastSimulatedDay: 1,
          region: 'east-blue',
          geography: ['sheltered stone harbor', 'windy northern road'],
          settlements: ['Gullrock Port', 'north-road hamlets'],
          resources: ['ship timber', 'salt', 'coastal trade'],
          opportunities: ['dock work', 'gear trade', 'bounty rumors', 'recruitment leads'],
          notableTraits: ['repair port', 'irregular Marine inspections'],
          governmentImportance: 0.22,
        },
      },
      encounters: [],
      knownGroups: {},
      recruitCandidates: {
        'mira-sorn': {
          id: 'mira-sorn',
          name: 'Mira Sorn',
          role: 'Field medic',
          locationId: 'gullrock-port',
          available: true,
          trust: 0.12,
          requiredTrust: 0.55,
          reasonToJoin: 'Mira wants passage away from Gullrock after settling a medical debt and needs evidence that a captain values people as more than expendable hands.',
          equipmentTags: ['medic', 'light-armor', 'tools', 'light-weapons'],
          capabilities: ['medicine', 'triage', 'support-combat'],
          personality: 'Practical, observant, skeptical of grand promises, and quick to notice how a captain treats injured people.',
          goals: ['Get clear of a local debt', 'Practice medicine at sea', 'Join people worth risking herself for'],
          fightingStyle: 'knife-and-baton self-defense with battlefield triage',
          visualArchetype: 'crew-medic',
          specialty: 0.24,
        },
      },
      threatHeat: 0,
    },
  };
}
